### ISSUE TITLE
Received status code 403 from server

### ISSUE THREAD

**Issue by dhiwakarmani** [Beanstream/beanstream-android-payform#10]
Hi There, 

I was trying to Integrate Android Library for PayForm and i am getting Error when i sync the project.

Error:Could not GET 'https://beanstream.jfrog.io/beanstream/libs-release/com/beanstream/android/payform/0.1.0/payform-0.1.0.pom'. Received status code 403 from server:

**Comment by dlight-bean** [comment]
The artifactory repository has been made public. You should be able to import it now.
